### PR TITLE
relaxed parser without schema verification

### PR DESCRIPTION
**Pull request by marcoist**

### CODE REVIEW

**Review by andyglow — APPROVED** [review]
lgtm

**Comment by marcoist** [comment]
Hi @andyglow ,

Are you making any release soon?

Regards,

**Comment by marcoist** [comment]
Hi @andyglow,

I saw that there is a new tag v0.7.3 but I didn't saw that version on central maven repository:

https://repo1.maven.org/maven2/com/github/andyglow/scala-jsonschema-parser_2.13/

Can you add that tag there please?

Regards,

**Comment by andyglow** [comment]
oh. sorry. something wrong had happened during release probably.
thanks for pinging me.. let me run release one more time

**Pull request merged**
