### PR TITLE
Changed internal container from unordered map to regular Seq.  

### LINKED ISSUE #108: Preserve original case class field ordering
When generating schemas, it could be helpful to keep original case class field ordering. It would make tests more readable.

### PR DESCRIPTION
**Pull request by michellemay**
Resolves #108

### CODE REVIEW

**Comment by andyglow** [comment]
Hey, thanks for the contribution first of all!

I found it a little difficult to review though, as the chance contain something that is not in direct correlation to the pull request and issue topic, right? JsonFormater for example.

And regarding the matter of the issue.. look, in order to minimize change, can we leverage scala.collection.immutable.ListMap? We wouldn't need extra opses, etc.

What do you think?

**Comment by michellemay** [comment]
I could split the PR and have the JsonFormatter in a different one..  However, I needed it in order to run tests locally.

As for the ListMap.. I'll have a look.

**Comment by michellemay** [comment]
It looks like ListMap are not sufficient to preserve order when updating/overwriting some keys in the map.

See:
```
scala> ListMap("a" -> 5, "b" -> 10) + ("a" -> 15)
res4: scala.collection.immutable.ListMap[String,Int] = Map(b -> 10, a -> 15)
```

After update, `a` change ordering.

**Comment by michellemay** [comment]
Do you want me to reopen the PR or you have other ideas ?

**Comment by randuhmm** [comment]
@michellemay @andyglow - Sorry to ping you both on such an old thread, but I am interested in preserving the original case class field ordering with this tool. I took a quick look and perhaps `scala.collection.immutable.SeqMap` could be an option for keeping insertion order and minimizing changes.

**Pull request closed without merging**
